# Generated by Django 2.0.6 on 2019-06-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDetails',
            fields=[
                ('name', models.CharField(default='', max_length=225)),
                ('email', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=225)),
                ('mobile', models.CharField(default='', max_length=225)),
                ('gender', models.CharField(default='', max_length=225, null=True)),
                ('address', models.CharField(default='', max_length=225, null=True)),
                ('otp', models.CharField(default='', max_length=225, null=True)),
                ('otp_time', models.CharField(default='', max_length=225, null=True)),
                ('last_login', models.CharField(default='', max_length=225, null=True)),
                ('active', models.CharField(default='', max_length=225)),
                ('verify_link', models.CharField(default='', max_length=225, null=True)),
                ('auth_token', models.CharField(default='', max_length=225, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_panel.UserRole')),
            ],
        ),
    ]
