# Generated by Django 2.0.6 on 2019-07-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_panel', '0002_roledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=225)),
                ('log_in', models.CharField(default='', max_length=225)),
                ('log_out', models.CharField(default='', max_length=225)),
                ('address', models.CharField(default='', max_length=225, null=True)),
            ],
        ),
    ]
